- name: Create users
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ common_users }}"

- name: Create groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ common_groups }}"

- name: Create files
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(None) }}"
  loop: "{{ common_file }}"

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(None) }}"
    mode: "{{ item.mode | default(None) }}"
    force: "{{ item.force | default(true) }}"
  loop: "{{ common_copy }}"

- name: Run shell commands
  shell:
    cmd: "{{ item.cmd }}"
    chdir: "{{ item.chdir }}"
  loop: "{{ common_shell }}"
