- name: Create common group
  group:
    name: "{{ common_group }}"
    state: present

- name: Create container user
  user:
    name: "{{ common_user }}"
    group: "{{ common_group }}"

- name: Create files
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  loop: "{{ common_files }}"
  become: true
  become_user: "{{ common_user }}"

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.group | default(None) }}"
    mode: "{{ item.mode | default(None) }}"
    force: "{{ item.force | default(true) }}"
  loop: "{{ common_copy }}"
  become: true
  become_user: "{{ common_user }}"

- name: Run shell commands
  shell:
    cmd: "{{ item.cmd }}"
    chdir: "{{ item.chdir }}"
  loop: "{{ common_shell }}"
  become: true
  become_user: "{{ common_user }}"
